import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
    
    
      <Head>
        <title>CodderHunts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="cooder hunts , nextjs, code Problem" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <nav className={styles.mainnav}>
     <ul>
    <Link href=" /"><a ><li>Home</li></a></Link> 
    <Link href="about"><a ><li>About </li></a></Link>
    <Link href="blog"><a ><li>Blogs</li></a></Link>
    <Link  href="contact"><a><li>Contact</li></a></Link>
   
     
     
     </ul>
     </nav>

      <main className={styles.main}>
        <h1 className={styles.title}> <span className="myspan">CodderHunts</span></h1>

        <p className={styles.description}>CodderHunts can solve your problem</p>

        <div className="blogs">
        <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn javascript</h3>
            <p>Javascript is a language to design a web application</p>
            {/*<Image src="https://unsplash.com/photos/i25aqE_YUZs" alt="image of javascript logo"/>*/}
          </div>
          <div className="blogItem">
            <h3>How to learn javascript</h3>
            <p>Javascript is a language to design a web application</p>
            {/*<Image src="https://unsplash.com/photos/i25aqE_YUZs" alt="image of javascript logo"/>*/}
          </div>
          <div className="blogItem">
            <h3>How to learn javascript</h3>
            <p>Javascript is a language to design a web application</p>
            {/*<Image src="https://unsplash.com/photos/i25aqE_YUZs" alt="image of javascript logo"/>*/}
          </div>
          <div className="blogItem">
            <h1>How to learn javascript</h1>
            <p>Javascript is a language to design a web application</p>
            {/*<Image src="https://unsplash.com/photos/i25aqE_YUZs" alt="image of javascript logo"/>*/}
          </div>
          <div className="blogItem">
            <h1>How to learn javascript</h1>
            <p>Javascript is a language to design a web application</p>
            {/*<Image src="https://unsplash.com/photos/i25aqE_YUZs" alt="image of javascript logo"/>*/}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
