import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
      {`
      h2{
        padding:10px;
      }
      `
      }</style>
    
      <Head>
        <title>CodderHunts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="cooder hunts , nextjs, code Problem" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main className={styles.main}>
        <h1 className={styles.title}> <span className="myspan">CodderHunts</span></h1>
        <Image src="/javascript.jpg" alt="img cant cload" width={1240} height={460} className={styles.homeimg} />

        <p className={styles.description}>CodderHunts can solve your problem</p>

        <div className="blogs">
        <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn javascript</h3>
            <p>Javascript is a language to design a web application</p>
            {/*<Image src="https://unsplash.com/photos/i25aqE_YUZs" alt="image of javascript logo"/>*/}
          </div>
          <div className="blogItem">
            <h3>How to learn javascript</h3>
            <p>Javascript is a language to design a web application</p>
            {/*<Image src="https://unsplash.com/photos/i25aqE_YUZs" alt="image of javascript logo"/>*/}
          </div>
          <div className="blogItem">
            <h3>How to learn javascript</h3>
            <p>Javascript is a language to design a web application</p>
            {/*<Image src="https://unsplash.com/photos/i25aqE_YUZs" alt="image of javascript logo"/>*/}
          </div>
          <div className="blogItem">
            <h3>How to learn javascript</h3>
            <p>Javascript is a language to design a web application</p>
            {/*<Image src="https://unsplash.com/photos/i25aqE_YUZs" alt="image of javascript logo"/>*/}
          </div>
          <div className="blogItem">
            <h3>How to learn javascript</h3>
            <p>Javascript is a language to design a web application</p>
            {/*<Image src="https://unsplash.com/photos/i25aqE_YUZs" alt="image of javascript logo"/>*/}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  );
}
